//;---------------------------------------
//;  CMT2300A Configuration File
//;  Generated by CMOSTEK RFPDK 1.53_Update4
//;  2023.03.13 17:23
//;---------------------------------------
//; Mode                      = Advanced
//; Part Number               = CMT2300A
//; Frequency                 = 915.000 MHz
//; Xtal Frequency            = 26.0000 MHz
//; Demodulation              = FSK
//; AGC                       = On
//; Data Rate                 = 1.2 kbps
//; Deviation                 = 20.0 kHz
//; Tx Xtal Tol.              = 10 ppm
//; Rx Xtal Tol.              = 10 ppm
//; TRx Matching Network Type = 20 dBm
//; Tx Power                  = +20 dBm
//; Gaussian BT               = NA
//; Bandwidth                 = Auto-Select kHz
//; CDR Type                  = Counting
//; CDR DR Range              = NA
//; AFC                       = On
//; AFC Method                = Auto-Select
//; Data Representation       = 0:F-low 1:F-high
//; Rx Duty-Cycle             = Off
//; Tx Duty-Cycle             = Off
//; Sleep Timer               = Off
//; Sleep Time                = NA
//; Rx Timer                  = Off
//; Rx Time T1                = NA
//; Rx Time T2                = NA
//; Rx Exit State             = SLEEP
//; Tx Exit State             = SLEEP
//; SLP Mode                  = Mode 13
//; RSSI Valid Source         = PJD
//; PJD Window                = 4 Jumps
//; LFOSC Calibration         = On
//; Xtal Stable Time          = 155 us
//; RSSI Compare TH           = NA
//; Data Mode                 = Packet
//; Whitening                 = Enable
//; Whiten Type               = PN9 CCITT
//; Whiten Seed Type          = NA
//; Whiten Seed               = 511
//; Manchester                = Disable
//; Manchester Type           = NA
//; FEC                       = Disable
//; FEC Type                  = NA
//; Tx Prefix Type            = 0
//; Tx Packet Number          = 1
//; Tx Packet Gap             = 32
//; Packet Type               = Variable Length
//; Node-Length Position      = First Node, then Length
//; Payload Bit Order         = Start from msb
//; Preamble Rx Size          = 1
//; Preamble Tx Size          = 8
//; Preamble Value            = 170
//; Preamble Unit             = 8-bit
//; Sync Size                 = 3-byte
//; Sync Value                = 13290067
//; Sync Tolerance            = None
//; Sync Manchester           = Disable
//; Node ID Size              = NA
//; Node ID Value             = NA
//; Node ID Mode              = None
//; Node ID Err Mask          = Disable
//; Node ID Free              = Disable
//; Payload Length            = 32
//; CRC Options               = IBM-16
//; CRC Seed                  = 65535 crc_seed
//; CRC Range                 = Entire Payload
//; CRC Swap                  = Start from MSB
//; CRC Bit Invert            = Normal
//; CRC Bit Order             = Start from bit 15
//; Dout Mute                 = Off
//; Dout Adjust Mode          = Disable
//; Dout Adjust Percentage    = NA
//; Collision Detect          = Off
//; Collision Detect Offset   = NA
//; RSSI Detect Mode          = Always
//; RSSI Filter Setting       = No Filtering
//; RF Performance            = High
//; LBD Threshold             = 2.4 V
//; RSSI Offset               = 0
//; RSSI Offset Sign          = 0
//;---------------------------------------
//;  The following are the Register contents
//;---------------------------------------
//;---------------------------------------
//;  The following is the CRC result for
//;  the above Register contents
//;---------------------------------------
// #include <arduino.h>
#include <stdint.h>

uint16_t CMTBank[12] = {
0x0000,
0x0166,
0x02EC,
0x031D,
0x04F0,
0x0580,
0x0614,
0x0708,
0x0811,
0x0902,
0x0A02,
0x0B00,
};

uint16_t SystemBank[12] = {
0x0CAE,
0x0DE0,
0x0E30,
0x0F00,
0x1000,
0x11F4,
0x1210,
0x13E2,
0x1442,
0x152D,
0x1600,
0x1701,
};

uint16_t FrequencyBank[8] = {
0x1846,
0x196D,
0x1A80,
0x1B86,
0x1C46,
0x1D62,
0x1E27,
0x1F16,
};

uint16_t DataRateBank[24] = {
0x2019,
0x210C,
0x2210,
0x23BB,
0x24E2,
0x25DE,
0x260C,
0x2705,
0x28DF,
0x2926,
0x2A29,
0x2B29,
0x2CC0,
0x2DA2,
0x2E54,
0x2F53,
0x3000,
0x3100,
0x32B4,
0x3300,
0x3400,
0x3501,
0x3600,
0x3700,
};

uint16_t BasebandBank[29] = {
0x380A,
0x3908,
0x3A00,
0x3BAA,
0x3C04,
0x3D00,
0x3E00,
0x3F00,
0x4000,
0x4100,
0x4253,
0x43CA,
0x44CA,
0x4501,
0x461F,
0x4700,
0x4800,
0x4900,
0x4A00,
0x4B00,
0x4C03,
0x4DFF,
0x4EFF,
0x4F64,
0x50FF,
0x5100,
0x5200,
0x531F,
0x5410,
};

uint16_t TXBank[11] = {
0x5550,
0x564D,
0x5706,
0x5800,
0x5986,
0x5AD0,
0x5B00,
0x5CC8,
0x5D10,
0x5E3F,
0x5F7F,
};
